### ISSUE TITLE
the Action Genome Dump frames of this paper

### ISSUE THREAD

**Issue by Yassin-fan** [yrcong/STTran#12]
In your readme, it is said to follow JingweiJ/ActionGenome to get the dataset. 
Could you please supply the version of your ffmpeg? For I followed JingweiJ/ActionGenome and get the empty folders of all the videos.
By the way, I'd like to know whether you use 'python tools/dump_frames.py --all_frames' or just 'python tools/dump_frames.py' to get the dataset?
Thanks for your work!

**Comment by entalent** [comment]
If you get empty folders, this is probably because there are some errors when executing the ffmpeg command. In [line 36 of dump_frames.py](https://github.com/JingweiJ/ActionGenome/blob/master/tools/dump_frames.py#L36), you can change `-loglevel panic` to `-loglevel verbose` to see the output of ffmpeg and know what happened when extracting the frames. You can also check whether the command in this line is correctly formatted.

**Comment by Yassin-fan** [comment]
> If you get empty folders, this is probably because there are some errors when executing the ffmpeg command. In [line 36 of dump_frames.py](https://github.com/JingweiJ/ActionGenome/blob/master/tools/dump_frames.py#L36), you can change `-loglevel panic` to `-loglevel verbose` to see the output of ffmpeg and know what happened when extracting the frames. You can also check whether the command in this line is correctly formatted.

Thanks for your help！ I sloved this proplem.
By the way, I ran the train.py code and it said that "fail on __ background __" after loading word vectors from glove.6B.200d.pt.
In my opinion, it is because that the word " __ background __" can not be found in glove, but how to slove this problem? Or just ignore it and wait for the result?

**Comment by yrcong** [comment]
> > If you get empty folders, this is probably because there are some errors when executing the ffmpeg command. In [line 36 of dump_frames.py](https://github.com/JingweiJ/ActionGenome/blob/master/tools/dump_frames.py#L36), you can change `-loglevel panic` to `-loglevel verbose` to see the output of ffmpeg and know what happened when extracting the frames. You can also check whether the command in this line is correctly formatted.
> 
> Thanks for your help！ I sloved this proplem. By the way, I ran the train.py code and it said that "fail on __ background __" after loading word vectors from glove.6B.200d.pt. In my opinion, it is because that the word " __ background __" can not be found in glove, but how to slove this problem? Or just ignore it and wait for the result?

You could easily ignore this:) The "__background__" is not included in the GloVe model, but we also didn't use it.
