### ISSUE TITLE
About SGCLS

### ISSUE THREAD

**Issue by qiuyue1993** [yrcong/STTran#14]
Hi!
I tried your code but I have found that the evaluation for sgcls is extremely low (near to 0) and the predcls and sgdet were the same with your paper. 
Could you please give me some hint about this problem or could you please check your code for sgcls again?
Thank you so much!

**Comment by qiuyue1993** [comment]
> Hi! I tried your code but I have found that the evaluation for sgcls is extremely low (near to 0) and the predcls and sgdet were the same with your paper. Could you please give me some hint about this problem or could you please check your code for sgcls again? Thank you so much!

I have made a mistake and the decoder_lin remained under-trained. Thank you so much! The problem is solved now!

**Comment by yrcong** [comment]
:)
