### ISSUE TITLE
About evaluation metrics

### ISSUE THREAD

**Issue by ghost** [yrcong/STTran#19]
您好，打扰了。我注意到在您的论文中 SGDET 的 Recall@10 指标 No Constraint 比 With Constraint 低，是什么原因造成这种情况的出现呀？一般情况下 No Constraint 不是应该比 With Constraint 高的吗？

**Comment by yrcong** [comment]
Hi 这个是因为我们使用了multi-label classification并且no constraint允许同一个pair输出多个predicate label造成的。比如一个false positive pair，subject和object的分数比其他true positive要高。而对于这个FP pair在no constraint下会输出多个无效的predicate，排在ranking list的前面部分。
