### ISSUE TITLE
use glove failed

### ISSUE THREAD

**Issue by ghostlyFeng** [yrcong/STTran#2]
Thanks for your codes, its helpful!
but some error happend when i run the Train command，error like this:
```
The CKPT saved here: data/
spatial encoder layer num: 1 / temporal decoder layer num: 3
mode : predcls
save_path : data/
model_path : None
data_path : /home/abc/NewDisk/origin_datasets/ActionGenome/dataset/ag/
datasize : large
ckpt : None
optimizer : adamw
lr : 1e-05
nepoch : 10
enc_layer : 1
dec_layer : 3
bce_loss : False
-------loading annotations---------slowly-----------
--------------------finish!-------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
There are 7584 videos and 177330 valid frames
144 videos are invalid (no person), remove them
49 videos are invalid (only one frame), remove them
21643 frames have no human bbox in GT, remove them!
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-------loading annotations---------slowly-----------
--------------------finish!-------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
There are 1750 videos and 56923 valid frames
41 videos are invalid (no person), remove them
19 videos are invalid (only one frame), remove them
8636 frames have no human bbox in GT, remove them!
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

loading word vectors from data/glove.6B.200d.pt
loading word vectors from /home/abc/NewDisk/model_zoo/STTran/glove.6B.200d.pt
__background__ -> __background__ 
fail on __background__
```
The program is stuck at this point, so i wonder why?
Thanks!

**Comment by yrcong** [comment]
By default, the print frequency is 1000 iterations. It seems the program is running.

**Comment by leonodelee** [comment]
> Thanks for your codes, its helpful! but some error happend when i run the Train command，error like this:
> 
> ```
> The CKPT saved here: data/
> spatial encoder layer num: 1 / temporal decoder layer num: 3
> mode : predcls
> save_path : data/
> model_path : None
> data_path : /home/abc/NewDisk/origin_datasets/ActionGenome/dataset/ag/
> datasize : large
> ckpt : None
> optimizer : adamw
> lr : 1e-05
> nepoch : 10
> enc_layer : 1
> dec_layer : 3
> bce_loss : False
> -------loading annotations---------slowly-----------
> --------------------finish!-------------------------
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> There are 7584 videos and 177330 valid frames
> 144 videos are invalid (no person), remove them
> 49 videos are invalid (only one frame), remove them
> 21643 frames have no human bbox in GT, remove them!
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> -------loading annotations---------slowly-----------
> --------------------finish!-------------------------
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> There are 1750 videos and 56923 valid frames
> 41 videos are invalid (no person), remove them
> 19 videos are invalid (only one frame), remove them
> 8636 frames have no human bbox in GT, remove them!
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> loading word vectors from data/glove.6B.200d.pt
> loading word vectors from /home/abc/NewDisk/model_zoo/STTran/glove.6B.200d.pt
> __background__ -> __background__ 
> fail on __background__
> ```
> 
> The program is stuck at this point, so i wonder why? Thanks!

Have you fixed it?

**Comment by yrcong** [comment]
It seems that the training has begun.

**Comment by FXLYZ** [comment]
@leonodelee I have same problem, have you solved it?

**Comment by LllHan** [comment]
请问解决了么？
