### ISSUE TITLE
About released pretrained models

### ISSUE THREAD

**Issue by Wh2018** [yrcong/STTran#20]
Hello, I try to used the pretrained models, but the three tar files appear to be corrupted, can you upload new models? Thanks
![image](https://user-images.githubusercontent.com/35520082/148868019-7298b9bf-0e4c-4343-8a3e-9a0b82cc6707.png)

**Comment by yrcong** [comment]
Hi, these tar files are not compressed files but already the checkpoints. You could use ```torch.load(''xxx.tar")``` directly.
