### ISSUE TITLE
Question of FastRCNN when using the sgdet mode

### ISSUE THREAD

**Issue by Wh2018** [yrcong/STTran#21]
Thanks for sharing the nice work!

I have successfully trained and tested the model in predcls mode, but when I want to train the model in the sgdet mode, I met a few problems.

In object_detector.py, fasterRCNN needs to return **five** values (Figure 1), but in faster_rnn.py, there are **eight** values to be retured (Figure 2), and there is no **roi_features** needed in object_detector.py

Could you tell me how to solve the problem requires, thank you very much
![1](https://user-images.githubusercontent.com/35520082/154496955-12d8a147-1301-473e-8cc4-0aac69e67ce9.jpg)
![2](https://user-images.githubusercontent.com/35520082/154496985-ea67ecf7-fcf0-4f9f-b277-7b639eb44ca1.jpg)

**Comment by yrcong** [comment]
Ye, we need return some features from the fasterrcnn. That's why the code is a little bit different.
