### ISSUE TITLE
Fail on __background

### ISSUE THREAD

**Issue by FXLYZ** [yrcong/STTran#23]
<img width="1710" alt="截屏2022-02-22 下午2 51 27" src="https://user-images.githubusercontent.com/47638930/155078491-3b64ce6d-9584-487d-9ac9-2512dd25a3a5.png">
when I train model, run command to PredCLS.

**Comment by yrcong** [comment]
It is not an error, we don't need this word embedding. _background_ is just a dummy label. You can ignore this.

**Comment by FXLYZ** [comment]
Thanks. 但是GPU利用率一直为0，显存占用也很低，似乎卡住了（GPU型号为3080Ti 12GB）。下图为Debug的断点：
![2022-02-23 23-14-25屏幕截图](https://user-images.githubusercontent.com/47638930/155348159-ada84fcd-25e9-4784-97d2-fafd1c0d803a.png)
![2022-02-23 23-16-09屏幕截图](https://user-images.githubusercontent.com/47638930/155348671-75f82c95-3557-4c75-8bd7-ee81bbc82be6.png)

**Comment by CL2LC** [comment]
您好，我这边因为CPU内存满了，卡住了，您是怎么解决的呢？
Hello, my side is stuck because the CPU memory is full, how do you solve it?
