### ISSUE TITLE
ffmpeg问题

### ISSUE THREAD

**Issue by wusuowei11** [yrcong/STTran#27]
执行生成帧代码时，我这生成都是空文件夹，显示这个sh: 1: ffmpeg: not found，请问是什么原因呢

**Comment by yrcong** [comment]
我不太清楚你説的生成幀代碼是哪個.py文件？

**Comment by wusuowei11** [comment]
感谢您的回复，之前的问题已经解决了，现在有个困惑地方想问您。原文中有提到这句话，The
threshold of confidence in the relationship is set to 0.9 in
Semi Constraint for all experiments if no special instruc-
tion.此处置信度阈值0.9是为何这样设置呢

**Comment by wusuowei11** [comment]
感谢您的回复，之前问题已经解决。现在我有个疑惑想请您帮忙解答。为了研究半限制条件下这种阈值对Recall@K的影响，STTran在0.7到0.95的所有阈值水平上一致地优于其他三个模型。那这个置信度阈值0.9是怎么确定的呢

**Comment by wusuowei11** [comment]
感谢您的回复，之前问题已经解决。现在我有个疑惑想请您帮忙解答。为了研究半限制条件下这种阈值对Recall@K的影响，STTran在0.7到0.95的所有阈值水平上一致地优于其他三个模型。那这个置信度阈值0.9是怎么确定的呢？
