### ISSUE TITLE
阈值0.9

### ISSUE THREAD

**Issue by wusuowei11** [yrcong/STTran#28]
我有个疑惑想请您帮忙解答。为了研究半限制条件下这种阈值对Recall@K的影响，STTran在0.7到0.95的所有阈值水平上一致地优于其他三个模型。那这个置信度阈值0.9是怎么确定的呢？

**Comment by yrcong** [comment]
That is just a hyperparameter:) You can change the confidence threshold in practical applications

**Comment by wusuowei11** [comment]
感谢您的回复，祝您一切顺利。
