### ISSUE TITLE
there is not object_bbox_and_relationship_filtersmall.pkl in /dataloader

### ISSUE THREAD

**Issue by PrimoWW** [yrcong/STTran#3]
I found if I want to use sgcls or sgdet mode, I needd this file.
So how can I gennrate it?

**Comment by yrcong** [comment]
Hi, You can generate it by yourself. Drop the boxes whose short edge<16 pixel.
I forgot to upload the file..

**Comment by yrcong** [comment]
I have put the link in the README. Thanks for the reminder :D
