### ISSUE TITLE
About the average precision of predicates

### ISSUE THREAD

**Issue by FXLYZ** [yrcong/STTran#31]
Hi,
Can you share the code of computing  the average precision of predicates?
Thank you! 😊 
<img width="1150" alt="截屏2022-05-16 15 35 13" src="https://user-images.githubusercontent.com/47638930/168545306-5a8f2db6-6315-4234-82be-b3c07e8a7486.png">

**Comment by yrcong** [comment]
Hi,

sry for the late reply. I
we used the standard evaluation metrics of OpenImages VRD Challenge. You can find it in the RelDN repo:
https://github.com/NVIDIA/ContrastiveLosses4VRD/blob/master/lib/datasets_rel/ap_eval_rel.py
