### ISSUE TITLE
Query about "Other Relationships"

### ISSUE THREAD

**Issue by ASMIftekhar** [yrcong/STTran#32]
Hello,
Thanks a lot your nice work.

In the paper, you mentioned to evaluate on 25 classes, however, in your dataloader you have "Other Relationships" as a contact class which makes in total 26 classes. Is there any particular reason for using it?

**Comment by yrcong** [comment]
Hi, 
sry for the late reply.
Actually, we also have no idea. We directly download the dataset from https://www.actiongenome.org/
Although the authors didn't show this category in the [original AG paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Ji_Action_Genome_Actions_As_Compositions_of_Spatio-Temporal_Scene_Graphs_CVPR_2020_paper.pdf), it exists...
We just follow the original annotation.
