### ISSUE TITLE
Broken  file for pretrained models

### ISSUE THREAD

**Issue by zee-fee** [yrcong/STTran#37]

**Comment by zee-fee** [comment]
I have tried to  unzip the downloaded  predcls [trained model](https://drive.google.com/file/d/1Sk5qFLWTZmwr63fHpy_C7oIxZSQU16vU/view) using the command 
`tar -xvf  predcls.tar`

 It always give the following error:
`tar: This does not look like a tar archive`

I'm assuming that the files were not compressed correctly. I tried this with the other provided pretrained models  ([sgcls](https://drive.google.com/file/d/1ZbJ7JkTEVM9mCI-9e5bCo6uDlKbWttgH/view)  and [sgdet](https://drive.google.com/file/d/1dBE90bQaXB-xogRdyAJa2A5S8RwYvjPp/view))and get the same error.

**Comment by yrcong** [comment]
Hi, I saved the pretrained model in .tar format.
Therefore you can directly use torch.load(), don't need to unzip them:D

**Comment by zee-fee** [comment]
@yrcong Thanks for the reply. It worked :)
