### ISSUE TITLE
about object_bbox

### ISSUE THREAD

**Issue by wusuowei11** [yrcong/STTran#40]
请问文件里面这个object_bbox标注位置信息的格式是什么，左上右下坐标（x1,y1,x2,y2）还是中心宽高坐标(x,y,w,h)呢

**Comment by zee-fee** [comment]
In Action Genome annotation, person_bbox has (xyxy) format and object boxes have (xywh) format. 
This is chnaged in the ActionGenome Dataset class, where all boxes are in xyxy format
Hope this helps :)

**Comment by wusuowei11** [comment]
感谢您的回复，我再确认一下，您是说object_bbox_and_relationship_filtersmall.pkl 和 object_bbox_and_relationship.pkl 中的object_bbox位置信息已经修改为（xyxy）格式了么

**Comment by zee-fee** [comment]
In object_bbox_and_relationship_filtersmall.pkl and object_bbox_and_relationship.pkl files, object bbox is in xywh format. It is converted to xyxy format in dataloader/action_genome.py line 133.

`k['bbox'] = np.array([k['bbox'][0], k['bbox'][1], k['bbox'][0]+k['bbox'][2], k['bbox'][1]+k['bbox'][3]]) # from xywh to xyxy`

**Comment by wusuowei11** [comment]
感谢您的回复，我理解您的意思啦。在Action Genome annotation的（xywh）格式中，xy是指边框的左上角顶点坐标。

**Comment by yrcong** [comment]
> 感谢您的回复，我理解您的意思啦。在Action Genome annotation的（xywh）格式中，xy是指边框的左上角顶点坐标。

I remember, in the original Action Genome annotations, "person" boxes are annotated with xywh, while the boxes of other classes are annotated in xyxy.

**Comment by zee-fee** [comment]
> 感谢您的回复，我理解您的意思啦。在Action Genome annotation的（xywh）格式中，xy是指边框的左上角顶点坐标。

That's correct.

**Comment by zee-fee** [comment]
Here is a jupyter notebook where I explored the dataset. Hope you find this helpful. [Notebook](https://github.com/zee-fee/Action_Genome/blob/main/Action_Genome_Boxes.ipynb)

**Comment by wusuowei11** [comment]
非常感谢您，这对我理解帮助很大。
