### ISSUE TITLE
关于训练过程的问题

### ISSUE THREAD

**Issue by huan-end** [yrcong/STTran#5]
作者你好，对于训练的过程我有些问题。整个系统在训练时候用来检测的fasterrcnn也一起跟着训练吗，还是说只是用来提取图片的特征？object_detector文件下的is_train代码的作用是什么呢？

**Comment by yrcong** [comment]
STTrans 是一个two stage的框架。Object detector (fasterRCNN) 先被预训练，然后在训练期间被冻结。当is_train为True时，则给出ground truth relationships (比如bbox1为subject，bbox2为object)用于训练，而这些信息在test时候不会给出，需要模型自己检测。

**Comment by huan-end** [comment]
> STTrans 是一个two stage的框架。Object detector (fasterRCNN) 先被预训练，然后在训练期间被冻结。当is_train为True时，则给出ground truth relationships (比如bbox1为subject，bbox2为object)用于训练，而这些信息在test时候不会给出，需要模型自己检测。

原来如此，谢谢！
