### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ParthaNanjanagud** [yrcong/STTran#59]
getting error while training the model, how can I solve this ? 

GPU A5000 ( cuda 12.2) - checked with watch command to check for out-of-memory issues, but GPU had substantial memory left. 

My env - 

python - 3.6 
torch - 1.1 
cuda - 10.0

how to solve this I have been trying for a week now! 

please help !

**Comment by langlangmingyue** [comment]
I have also encountered this problem. Could you please tell me how you solved it? Thank you very much.
