### ISSUE TITLE
关于object_detector.py下的sptial_mask的问题

### ISSUE THREAD

**Issue by lalalababa** [yrcong/STTran#6]
作者你好，请问sptial_mask代表着什么呢？

**Comment by yrcong** [comment]
Hi，这是用于表达物体位置信息的binary mask, foreground为1，background为0。可以看看 https://arxiv.org/pdf/2107.12309.pdf 中的Figure 6。

**Comment by lalalababa** [comment]
> Hi，这是用于表达物体位置信息的binary mask, foreground为1，background为0。可以看看 https://arxiv.org/pdf/2107.12309.pdf 中的Figure 6。

我明白了，非常感谢！
