### ISSUE TITLE
关于usage

### ISSUE THREAD

**Issue by ZihaoZheng98** [yrcong/STTran#7]
您好，关于usage那里我没看明白，clone完之后应该怎么操作？clone完之后运行下面五行代码，然后把pth模型放在对应目录，然后就能开始跑下面的实验代码了吗？

**Comment by lalalababa** [comment]
> 您好，关于usage那里我没看明白，clone完之后应该怎么操作？clone完之后运行下面五行代码，然后把pth模型放在对应目录，然后就能开始跑下面的实验代码了吗？

fasterrcnn那块也要编译一下，不过在编译之前要先把作者编译好的东西删掉，不然会编译失败。

**Comment by ZihaoZheng98** [comment]
您好，我之前没用过faster-rcnn,所以不太懂这个过程，是我把作者fasterrcnn文件夹里的东西换成 https://github.com/jwyang/faster-rcnn.pytorch 里的内容，然后按readme编译，编译完成后把那个pth放进去，是这样吗 @lalalababa

**Comment by yrcong** [comment]
对，但是需要注意fasterrcnn有的地方我修改了下用来return feature maps，

**Comment by ZihaoZheng98** [comment]
嗯嗯 好的 谢谢！

**Comment by lalalababa** [comment]
> 您好，我之前没用过faster-rcnn,所以不太懂这个过程，是我把作者fasterrcnn文件夹里的东西换成 https://github.com/jwyang/faster-rcnn.pytorch 里的内容，然后按readme编译，编译完成后把那个pth放进去，是这样吗 @lalalababa

你可以试试作者所说的办法，我是对照着jwyang的代码目录把fasterRcnn/lib/model文件夹下的编译文件删了，然后重新编译的。

**Comment by yrcong** [comment]
> > 您好，我之前没用过faster-rcnn,所以不太懂这个过程，是我把作者fasterrcnn文件夹里的东西换成 https://github.com/jwyang/faster-rcnn.pytorch 里的内容，然后按readme编译，编译完成后把那个pth放进去，是这样吗 @lalalababa
> 
> 你可以试试作者所说的办法，我是对照着jwyang的代码目录把fasterRcnn/lib/model文件夹下的编译文件删了，然后重新编译的。

主要是大家的cuda和gpu型号不同，编译起来就比较麻烦:(
不过我的下一个work就不会有这个问题了，不需要编译，全部是pytorch代码

**Comment by ZihaoZheng98** [comment]
> > > 您好，我之前没用过faster-rcnn,所以不太懂这个过程，是我把作者fasterrcnn文件夹里的东西换成 https://github.com/jwyang/faster-rcnn.pytorch 里的内容，然后按readme编译，编译完成后把那个pth放进去，是这样吗 @lalalababa
> > 
> > 
> > 你可以试试作者所说的办法，我是对照着jwyang的代码目录把fasterRcnn/lib/model文件夹下的编译文件删了，然后重新编译的。
> 
> 主要是大家的cuda和gpu型号不同，编译起来就比较麻烦:(
> 不过我的下一个work就不会有这个问题了，不需要编译，全部是pytorch代码

可以 话说你用的cuda版本是多少，我这有2080ti的显卡，我寻思直接按照你的cuda版本下一个得了。 话说下一个工作还是做这个任务吗

**Comment by lalalababa** [comment]
> > > > 您好，我之前没用过faster-rcnn,所以不太懂这个过程，是我把作者fasterrcnn文件夹里的东西换成 https://github.com/jwyang/faster-rcnn.pytorch 里的内容，然后按readme编译，编译完成后把那个pth放进去，是这样吗 @lalalababa
> > > 
> > > 
> > > 你可以试试作者所说的办法，我是对照着jwyang的代码目录把fasterRcnn/lib/model文件夹下的编译文件删了，然后重新编译的。
> > 
> > 
> > 主要是大家的cuda和gpu型号不同，编译起来就比较麻烦:(
> > 不过我的下一个work就不会有这个问题了，不需要编译，全部是pytorch代码
> 
> 可以 话说你用的cuda版本是多少，我这有2080ti的显卡，我寻思直接按照你的cuda版本下一个得了。 话说下一个工作还是做这个任务吗

我用的10.0，是可以跑的

**Comment by ZihaoZheng98** [comment]
哇  好像终于跑起来了，作者小哥哥能帮我看一下有没有错误的打印信息吗
(py36) [zhzheng@gpu25 STTran]$ python train.py -mode predcls -datasize large -data_path /users5/zhzheng/ActionGenome/dataset/ag/
The CKPT saved here: data/
spatial encoder layer num: 1 / temporal decoder layer num: 3
mode : predcls
save_path : data/
model_path : None
data_path : /users5/zhzheng/ActionGenome/dataset/ag/
datasize : large
ckpt : None
optimizer : adamw
lr : 1e-05
nepoch : 10
enc_layer : 1
dec_layer : 3
bce_loss : False
-------loading annotations---------slowly-----------
--------------------finish!-------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
There are 7584 videos and 177330 valid frames
144 videos are invalid (no person), remove them
49 videos are invalid (only one frame), remove them
21643 frames have no human bbox in GT, remove them!
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-------loading annotations---------slowly-----------
--------------------finish!-------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
There are 1750 videos and 56923 valid frames
41 videos are invalid (no person), remove them
19 videos are invalid (only one frame), remove them
8636 frames have no human bbox in GT, remove them!
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
loading word vectors from data/glove.6B.200d.pt
loading word vectors from /users5/zhzheng/Dokumente/neural-motifs-master/data/glove.6B.200d.pt
__background__ -> __background__
fail on __background__

我创建了py3.6的环境，然后按照conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch安装了cudatoolkit100版本的torch，重新编译的话，实在是难顶...我们用实验室的服务器，不太方便自己装cuda然后编译那个代码

**Comment by ZihaoZheng98** [comment]
> > > > > 您好，我之前没用过faster-rcnn,所以不太懂这个过程，是我把作者fasterrcnn文件夹里的东西换成 https://github.com/jwyang/faster-rcnn.pytorch 里的内容，然后按readme编译，编译完成后把那个pth放进去，是这样吗 @lalalababa
> > > > 
> > > > 
> > > > 你可以试试作者所说的办法，我是对照着jwyang的代码目录把fasterRcnn/lib/model文件夹下的编译文件删了，然后重新编译的。
> > > 
> > > 
> > > 主要是大家的cuda和gpu型号不同，编译起来就比较麻烦:(
> > > 不过我的下一个work就不会有这个问题了，不需要编译，全部是pytorch代码
> > 
> > 
> > 可以 话说你用的cuda版本是多少，我这有2080ti的显卡，我寻思直接按照你的cuda版本下一个得了。 话说下一个工作还是做这个任务吗
> 
> 我用的10.0，是可以跑的

谢谢！

**Comment by ZihaoZheng98** [comment]
Hi, 我predcls没有问题，剩下两个任务在第一个epoch没问题，但是第二个epoch上会出现
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    pred = model(entry)
  File "/users5/zhzheng/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/users5/zhzheng/STTran/lib/sttran.py", line 323, in forward
    vr = self.union_func1(entry['union_feat'])+self.conv(entry['spatial_masks'])
KeyError: 'union_feat
请问作者遇到过这种情况吗，没有的话我就自己找找错误

**Comment by ZihaoZheng98** [comment]
哦哦 我找到错误了 在  train.py的  object_detector.train_x = True 84行，这里应该是设置is_train吧？ 
@yrcong

**Comment by yrcong** [comment]
> 哦哦 我找到错误了 在 train.py的 object_detector.train_x = True 84行，这里应该是设置is_train吧？
> @yrcong

Training的时候is_train是设置成True的

**Comment by ZihaoZheng98** [comment]
> > 哦哦 我找到错误了 在 train.py的 object_detector.train_x = True 84行，这里应该是设置is_train吧？
> > @yrcong
> 
> Training的时候is_train是设置成True的

哦 是的 但是train的代码逻辑，test那一步会把is_train设置为False，然后再train的第一步是train_x为True，第二个epoch就出问题了，然后我也没找到这个train_x在其他地方出现，你看看这个train_x是不是应该改成is_train?

**Comment by yrcong** [comment]
> > > 哦哦 我找到错误了 在 train.py的 object_detector.train_x = True 84行，这里应该是设置is_train吧？
> > > @yrcong
> > 
> > 
> > Training的时候is_train是设置成True的
> 
> 哦 是的 但是train的代码逻辑，test那一步会把is_train设置为False，然后再train的第一步是train_x为True，第二个epoch就出问题了，然后我也没找到这个train_x在其他地方出现，你看看这个train_x是不是应该改成is_train?

对对！我整理代码的时候漏掉了！感谢提醒

**Comment by ZihaoZheng98** [comment]
啊 可能是最后一个问题了hhh 论文中的数据是训练了多少轮的结果啊

**Comment by yrcong** [comment]
> 啊 可能是最后一个问题了hhh 论文中的数据是训练了多少轮的结果啊

5-10 epoch

**Comment by ZihaoZheng98** [comment]
> > 啊 可能是最后一个问题了hhh 论文中的数据是训练了多少轮的结果啊
> 
> 5-10 epoch

好的好的 感谢答疑！祝工作顺利。

**Comment by yrcong** [comment]
> > > 啊 可能是最后一个问题了hhh 论文中的数据是训练了多少轮的结果啊
> > 
> > 
> > 5-10 epoch
> 
> 好的好的 感谢答疑！祝工作顺利。

投个币吧，哦不star一下吧XD

**Comment by Yassin-fan** [comment]
> 对，但是需要注意fasterrcnn有的地方我修改了下用来return feature maps
> https://github.com/yrcong/STTran/blob/main/fasterRCNN/lib/model/faster_rcnn/faster_rcnn.py的112行 return rois, cls_prob, bbox_pred, base_feat, pooled_feat #if dynamic scene graph

您好，打扰了！请问目前编译 jwyang/faster-rcnn.pytorch，是需要将您仓库中的fasterRCNN目录下文件替换为https://github.com/jwyang/faster-rcnn.pytorch中文件、修改https://github.com/yrcong/STTran/blob/main/fasterRCNN/lib/model/faster_rcnn/faster_rcnn.py中代码，然后按照 jwyang/faster-rcnn.pytorch 的readme要求进行编译吗？
